cveloper/src/Entity/DevTech.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DevTechRepository")
 */
class DevTech
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Technology", inversedBy="devTeches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_tech;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Developer", inversedBy="devTeches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_developer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdTech(): ?Technology
    {
        return $this->id_tech;
    }

    public function setIdTech(?Technology $id_tech): self
    {
        $this->id_tech = $id_tech;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getIdDeveloper(): ?Developer
    {
        return $this->id_developer;
    }

    public function setIdDeveloper(?Developer $id_developer): self
    {
        $this->id_developer = $id_developer;

        return $this;
    }

    public function __toString()
    {
        return $this->id. ". D#" . $this->id_developer . " T#" . $this->id_tech . " L#" . $this->level;
    }
}

cveloper/src/Entity/Developer.php
<?php

namespace App\Entity;

// Lineas añadidas para VichUploader
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DeveloperRepository")
 * @Vich\Uploadable
 */
class Developer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $web;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Experience", mappedBy="id_developer", orphanRemoval=true)
     */
    private $experiences;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Training", mappedBy="id_developer", orphanRemoval=true)
     */
    private $trainings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Additional", mappedBy="id_developer", orphanRemoval=true)
     */
    private $additionals;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DevTech", mappedBy="id_developer", orphanRemoval=true)
     */
    private $devTeches;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="developer", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @Vich\UploadableField(mapping="developer_avatar", fileNameProperty="avatar")
     * @var File
     */
    private $imageFile;


    public function __construct()
    {
        $this->experiences = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->additionals = new ArrayCollection();
        $this->devTeches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(?string $github): self
    {
        $this->github = $github;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Experience[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setIdDeveloper($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): self
    {
        if ($this->experiences->contains($experience)) {
            $this->experiences->removeElement($experience);
            // set the owning side to null (unless already changed)
            if ($experience->getIdDeveloper() === $this) {
                $experience->setIdDeveloper(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Training[]
     */
    public function getTrainings(): Collection
    {
        return $this->trainings;
    }

    public function addTraining(Training $training): self
    {
        if (!$this->trainings->contains($training)) {
            $this->trainings[] = $training;
            $training->setIdDeveloper($this);
        }

        return $this;
    }

    public function removeTraining(Training $training): self
    {
        if ($this->trainings->contains($training)) {
            $this->trainings->removeElement($training);
            // set the owning side to null (unless already changed)
            if ($training->getIdDeveloper() === $this) {
                $training->setIdDeveloper(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Additional[]
     */
    public function getAdditionals(): Collection
    {
        return $this->additionals;
    }

    public function addAdditional(Additional $additional): self
    {
        if (!$this->additionals->contains($additional)) {
            $this->additionals[] = $additional;
            $additional->setIdDeveloper($this);
        }

        return $this;
    }

    public function removeAdditional(Additional $additional): self
    {
        if ($this->additionals->contains($additional)) {
            $this->additionals->removeElement($additional);
            // set the owning side to null (unless already changed)
            if ($additional->getIdDeveloper() === $this) {
                $additional->setIdDeveloper(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->id. ". " . $this->first_name . " " . $this->last_name;
    }

    /**
     * @return Collection|DevTech[]
     */
    public function getDevTeches(): Collection
    {
        return $this->devTeches;
    }

    public function addDevTech(DevTech $devTech): self
    {
        if (!$this->devTeches->contains($devTech)) {
            $this->devTeches[] = $devTech;
            $devTech->setIdDeveloper($this);
        }

        return $this;
    }

    public function removeDevTech(DevTech $devTech): self
    {
        if ($this->devTeches->contains($devTech)) {
            $this->devTeches->removeElement($devTech);
            // set the owning side to null (unless already changed)
            if ($devTech->getIdDeveloper() === $this) {
                $devTech->setIdDeveloper(null);
            }
        }

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getImageFile()
   {
       return $this->imageFile;
   }

   public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updated = new \DateTime('now');
        }
    }

   public function setImage($image)
   {
       $this->image = $image;
   }
}

cveloper/src/Form/DeveloperType.php
<?php

namespace App\Form;

use App\Entity\Developer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

class DeveloperType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name', TextType::class, ['label' => 'Nombre'])
            ->add('last_name' , TextType::class, ['label' => 'Apellidos'])
            ->add('address', TextType::class, ['label' => 'Dirección'])
            ->add('postal_code', NumberType::class, ['label' => 'Código Postal'])
            ->add('city', TextType::class, ['label' => 'Ciudad'])
            ->add('phone', NumberType::class, ['label' => 'Teléfono'])
            ->add('github', TextType::class, ['label' => 'Github'])
            ->add('linkedin', TextType::class, ['label' => 'Linkedin'])
            ->add('web', TextType::class, ['label' => 'Web'])
            ->add('email', EmailType::class, ['label' => 'Email'])
            //->add('avatar')
            //->add('id_user')
            //->add('devTeches')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Developer::class,
        ]);
    }
}

cveloper/src/Controller/DeveloperController.php
<?php

namespace App\Controller;

use App\Entity\Developer;
use App\Form\DeveloperType;
use App\Repository\DeveloperRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/developer/personal")
 */
class DeveloperController extends AbstractController
{
    /**
     * @Route("/", name="developer_index", methods={"GET"})
     */
    public function index(DeveloperRepository $developerRepository): Response
    {
        // modifico esto porque quiero que sólo muestre sus propios datos
        // return $this->render('developer/index.html.twig', [
        //     'developers' => $developerRepository->findAll(),
        // ]);

        // recojo el id_developer de la session del usuario-desarrollador
        $id = $this->get('session')->get('myDeveloperId');

        // pinto el template correspondiente al home de developer
        return $this->render('developer/home.html.twig', [
            // creo un nuevo método con la consulta restringida a su id
            'developer' => $developerRepository->findMe($id),
            'page_title' => 'Página Personal',
        ]);
    }

    /**
     * @Route("/new", name="developer_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $developer = new Developer();
        $form = $this->createForm(DeveloperType::class, $developer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($developer);
            $entityManager->flush();

            return $this->redirectToRoute('developer_index');
        }

        return $this->render('developer/new.html.twig', [
            'developer' => $developer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="developer_show", methods={"GET"})
     */
    public function show(Developer $developer): Response
    {
        return $this->render('developer/show.html.twig', [
            'developer' => $developer,
        ]);
    }

    /**
     * @Route("/cv/{id}", name="developer_cv", methods={"GET"})
     */
    public function cv(Developer $developer): Response
    {
        return $this->render('developer/cv.html.twig', [
            'developer' => $developer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="developer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Developer $developer): Response
    {
        $form = $this->createForm(DeveloperType::class, $developer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('developer_index', [
                'id' => $developer->getId(),
            ]);
        }

        return $this->render('developer/edit.html.twig', [
            'developer' => $developer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="developer_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Developer $developer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$developer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($developer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('developer_index');
    }
}

cveloper/templates/developer/_delete_form.html.twig
<form method="post" action="{{ path('developer_delete', {'id': developer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ developer.id) }}">
    <button class="btn">Borrar</button>
</form>

cveloper/templates/developer/cv.html.twig
{% extends 'base.html.twig' %}

{% block title %}CV{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row"><br><br></div>
    <div class="row">
        <div class="col-4 cv">
            <h2><br><b>{{ developer.firstName }}<br>{{ developer.lastName }}</b></h2>
        </div>
        <div class="col-8">
            <hr>
            {% for experience in developer.experiences %}
            <div class="row">
                <div class="col-2">
                    <p>{{ experience.city }}</p>
                </div>
                <div class="col-10">
                    <p>{{ experience.position }} en {{ experience.company }}</p>
                </div>
            </div>
            {% endfor %}
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4 cv">
            <img class="cv" src="/uploads/images/developer/avatar/{{ developer.avatar }}" />
        </div>
        <div class="col-8">
            <div class="row">
                <div class="col-2">
                    <p>PHP<br>
                    <br>Javascript<br>
                    <br>HTML<br>
                    <br>Java SE</p>
                </div>
                <div class="col-4">
                    <p>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    </p>
                </div>
                <div class="col-2">
                    <p>CSS<br>
                    <br>Joomla<br>
                    <br>Windows<br>
                    <br>Linux</p>
                </div>
                <div class="col-4">
                    <p>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                        <i class="far fa-circle"></i>
                    <br><br>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle"></i>
                        <i class="far fa-circle"></i>
                    </p>
                </div>
            </div>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4 cv"><br>
            <p><i class="fas fa-link"></i> {{ developer.web }}</p>
            <p><i class="fas fa-at"></i> {{ developer.email }}</p>
            <p><i class="fas fa-mobile-alt"></i> {{ developer.phone }}</p>
            <p><i class="fas fa-map-marker-alt"></i> {{ developer.city }}</p>
        </div>
        <div class="col-8">
            {% for training in developer.trainings %}
            <div class="row">
                <div class="col-2">
                    <p>{{ training.city }}</p>
                </div>
                <div class="col-10">
                    <p>{{ training.degree }} en {{ training.institution }}</p>
                </div>
            </div>
            {% endfor %}
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4 cv">
        </div>
        <div class="col-8">
            {% for additional in developer.additionals %}
                <p>{{ additional.description }}</p>
            {% endfor %}
            <hr>
        </div>
    </div>
</div>

{% endblock %}

cveloper/templates/developer/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block header %}
    {% include 'home/header.html.twig' %}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>{{ page_title }} de {{ app.user.username }}</h2>
        </div>
    <div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <tbody>
                    <tr>
                        <th>· · · · · · · · · · · · · · · · · ·</th>
                        <td><b>DATOS PERSONALES</b></td>
                        <td><a href="{{ path('developer_edit', {'id': developer.id}) }}">editar datos personales</a></td>
                    </tr>
                    <tr>
                        <th>Currículum</th>
                        <td>https://cveloper.com{{ path('developer_cv', {'id': developer.id}) }}</td>
                        <td><a target="_blank" href="{{ path('developer_cv', {'id': developer.id}) }}">ver currículum</a></td>
                    </tr>
                    <tr>
                        <th>Nombre</th>
                        <td>{{ developer.firstName }} {{ developer.lastName }}</td>
                        <td></td>
                    </tr>
                    <tr>
                        <th>Dirección</th>
                        <td>{{ developer.address }} {{ developer.postalCode }} {{ developer.city }}</td>
                        <td></td>
                    </tr>
                    <tr>
                        <th>Contacto</th>
                        <td>
                            <a href="tel:+34{{ developer.phone }}"><i class="fas fa-phone"></i></a>
                            <a href="mailto:{{ developer.email }}"><i class="fas fa-at"></i></a>
                            <a href="{{ developer.web }}"><i class="fab fa-internet-explorer"></i></a>
                            <a href="{{ developer.github }}"><i class="fab fa-github"></i></a>
                            <a href="{{ developer.linkedin }}"><i class="fab fa-linkedin-in"></i></a>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <th>Avatar</th>
                        <td><img class="dev_avatar" src="/uploads/images/developer/avatar/{{ developer.avatar }}" /></td>
                        <td></td>
                    </tr>
                    <tr>
                        <th>· · · · · · · · · · · · · · · · · ·</th>
                        <td><b>EXPERIENCIA</b></td>
                        <td><a href="{{ path('experience_index', {'id': developer.id}) }}">editar experiencia</a></td>
                    </tr>
                    {% for experience in developer.experiences %}
                    <tr>
                        <th>{{ experience.city }}</th>
                        <td>{{ experience.position }} en {{ experience.company }}</td>
                        <td><a href="{{ path('experience_edit', {'id': experience.id}) }}">editar</a></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th>· · · · · · · · · · · · · · · · · ·</th>
                        <td><b>FORMACIÓN</b></td>
                        <td><a href="{{ path('training_index', {'id': developer.id}) }}">editar formación</a></td>
                    </tr>
                    {% for training in developer.trainings %}
                    <tr>
                        <th>{{ training.city }}</th>
                        <td>{{ training.degree }} en {{ training.institution }}</td>
                        <td><a href="{{ path('training_edit', {'id': training.id}) }}">editar</a></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th>· · · · · · · · · · · · · · · · · ·</th>
                        <td><b>INFORMACIÓN ADICIONAL</b></td>
                        <td><a href="{{ path('additional_index', {'id': developer.id}) }}">editar adicionales</a></td>
                    </tr>
                    {% for additional in developer.additionals %}
                    <tr>
                        <th></th>
                        <td>{{ additional.description }}</td>
                        <td><a href="{{ path('additional_edit', {'id': additional.id}) }}">editar</a></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th>· · · · · · · · · · · · · · · · · ·</th>
                        <td><b>DESTREZA EN TECNOLOGÍAS</b></td>
                        <td><a href="{{ path('dev_tech_index', {'id': developer.id}) }}">editar destrezas</a></td>
                    </tr>
                    {% for devTech in developer.devTeches %}
                    <tr>
                        <th><img class="dev_tech_logo" src="/uploads/images/technology/logo/{{ devTech.idTech.logo }}"></th>
                        <td>Nivel {{ devTech.level }} en {{ devTech.idTech.name }}</td>
                        <td><a href="{{ path('dev_tech_edit', {'id': devTech.id}) }}">editar</a></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <th><a href="https://cveloper.com/issue/">SOLICITAR UNA TECNOLOGÍA</a></th>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

    {#
    <a href="{{ path('developer_index') }}">back to list</a>
    <a href="{{ path('developer_edit', {'id': developer.id}) }}">edit</a>
    {{ include('developer/_delete_form.html.twig') }}
    #}
{% endblock %}

cveloper/templates/developer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Developer index{% endblock %}

{% block body %}

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    {{ dump(app.user) }}
    <p>Bienvenido {{ app.user.username }} !!!</p>
    <p>Tu id de usuario es: {{ app.user.id }}</p>
    <p>Tu id de desarrollador es: {{ app.user.developer.id }}</p>
{% endif %}

    <h1>Developer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Address</th>
                <th>Postal_code</th>
                <th>City</th>
                <th>Phone</th>
                <th>Github</th>
                <th>Linkedin</th>
                <th>Web</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for developer in developers %}
            <tr>
                <td>{{ developer.id }}</td>
                <td>{{ developer.firstName }}</td>
                <td>{{ developer.lastName }}</td>
                <td>{{ developer.address }}</td>
                <td>{{ developer.postalCode }}</td>
                <td>{{ developer.city }}</td>
                <td>{{ developer.phone }}</td>
                <td>{{ developer.github }}</td>
                <td>{{ developer.linkedin }}</td>
                <td>{{ developer.web }}</td>
                <td>{{ developer.email }}</td>
                <td>
                    <a href="{{ path('developer_show', {'id': developer.id}) }}">show</a>
                    <a href="{{ path('developer_edit', {'id': developer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('developer_new') }}">Create new</a>
{% endblock %}

cveloper/templates/developer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Developer{% endblock %}

{% block body %}
    <h1>Developer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ developer.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ developer.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ developer.lastName }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ developer.address }}</td>
            </tr>
            <tr>
                <th>Postal_code</th>
                <td>{{ developer.postalCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ developer.city }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ developer.phone }}</td>
            </tr>
            <tr>
                <th>Github</th>
                <td>{{ developer.github }}</td>
            </tr>
            <tr>
                <th>Linkedin</th>
                <td>{{ developer.linkedin }}</td>
            </tr>
            <tr>
                <th>Web</th>
                <td>{{ developer.web }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ developer.email }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('developer_index') }}">back to list</a>

    <a href="{{ path('developer_edit', {'id': developer.id}) }}">edit</a>

    {{ include('developer/_delete_form.html.twig') }}
{% endblock %}