cveloper/src/Entity/Experience.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExperienceRepository")
 */
class Experience
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Developer", inversedBy="experiences")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_developer;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_from;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_to;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getIdDeveloper(): ?Developer
    {
        return $this->id_developer;
    }

    public function setIdDeveloper(?Developer $id_developer): self
    {
        $this->id_developer = $id_developer;

        return $this;
    }

    public function getDateFrom(): ?\DateTimeInterface
    {
        return $this->date_from;
    }

    public function setDateFrom(\DateTimeInterface $date_from): self
    {
        $this->date_from = $date_from;

        return $this;
    }

    public function getDateTo(): ?\DateTimeInterface
    {
        return $this->date_to;
    }

    public function setDateTo(?\DateTimeInterface $date_to): self
    {
        $this->date_to = $date_to;

        return $this;
    }
}

cveloper/src/Form/ExperienceType.php
<?php

namespace App\Form;

use App\Entity\Experience;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
class ExperienceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('position', TextType::class, ['label' => 'Posicion'])
            ->add('company', TextType::class, ['label' => 'Compañía'])
            ->add('city', TextType::class, ['label' => 'Ciudad'])
            ->add('date_from', DateType::class, ['label' => 'Desde'])
            ->add('date_to', DateType::class, ['label' => 'Hasta'])
            ->add('id_developer')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Experience::class,
        ]);
    }
}

cveloper/src/Controller/ExperienceController.php
<?php

namespace App\Controller;

use App\Entity\Experience;
use App\Form\ExperienceType;
use App\Repository\ExperienceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/developer/experience")
 */
class ExperienceController extends AbstractController
{
    /**
     * @Route("/", name="experience_index", methods={"GET"})
     */
    public function index(ExperienceRepository $experienceRepository): Response
    {
        return $this->render('experience/index.html.twig', [
            'experiences' => $experienceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="experience_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $experience = new Experience();
        $form = $this->createForm(ExperienceType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($experience);
            $entityManager->flush();

            return $this->redirectToRoute('experience_index');
        }

        return $this->render('experience/new.html.twig', [
            'experience' => $experience,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="experience_show", methods={"GET"})
     */
    public function show(Experience $experience): Response
    {
        return $this->render('experience/show.html.twig', [
            'experience' => $experience,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="experience_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Experience $experience): Response
    {
        $form = $this->createForm(ExperienceType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('experience_index', [
                'id' => $experience->getId(),
            ]);
        }

        return $this->render('experience/edit.html.twig', [
            'experience' => $experience,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="experience_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Experience $experience): Response
    {
        if ($this->isCsrfTokenValid('delete'.$experience->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($experience);
            $entityManager->flush();
        }

        return $this->redirectToRoute('experience_index');
    }
}

cveloper/templates/experience/_delete_form.html.twig
<form method="post" action="{{ path('experience_delete', {'id': experience.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ experience.id) }}">
    <button class="btn">Borrar</button>
</form>

cveloper/templates/experience/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

cveloper/templates/experience/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Experiencia{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block header %}
    {% include 'home/header.html.twig' %}
{% endblock %}

{% block body %}
    <h1>Editar Experiencia</h1>
              {{ include('experience/_form.html.twig', {'button_label': 'Actualizar Datos'}) }}
                <a href="{{ path('experience_index') }}">Volver al Listado</a>
        {{ include('experience/_delete_form.html.twig', {'button_label': 'Borrar'}) }}
{% endblock %}

cveloper/templates/experience/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listado Experiencias{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block header %}
    {% include 'home/header.html.twig' %}
{% endblock %}

{% block body %}
    <h1>Listado de Experiencias</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Puesto</th>
                <th>Compañía</th>
                <th>Ciudad</th>
                <th>Desde</th>
                <th>Hasta</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for experience in experiences %}
            <tr>
                <td>{{ experience.id }}</td>
                <td>{{ experience.position }}</td>
                <td>{{ experience.company }}</td>
                <td>{{ experience.city }}</td>
                <td>{{ experience.dateFrom ? experience.dateFrom|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ experience.dateTo ? experience.dateTo|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('experience_show', {'id': experience.id}) }}">Mostrar</a>
                    <a href="{{ path('experience_edit', {'id': experience.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No se han encontrado Datos</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('experience_new') }}">Añadir Experiencia</a>
{% endblock %}

cveloper/templates/experience/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listado Experiencias{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block header %}
    {% include 'home/header.html.twig' %}
{% endblock %}
{% block body %}
    <h1>Añadir Nueva Experiencia</h1>

    {{ include('experience/_form.html.twig') }}

    <a href="{{ path('experience_index') }}">Volver al Listado</a>
{% endblock %}

cveloper/templates/experience/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Experiencia{% endblock %}

{% block stylesheets %}
    {% include 'home/styles.html' %}
{% endblock %}

{% block header %}
    {% include 'home/header.html.twig' %}
{% endblock %}
{% block body %}
    <h1>Experiencia</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ experience.id }}</td>
            </tr>
            <tr>
                <th>Puesto</th>
                <td>{{ experience.position }}</td>
            </tr>
            <tr>
                <th>Compañía</th>
                <td>{{ experience.company }}</td>
            </tr>
            <tr>
                <th>Ciudad</th>
                <td>{{ experience.city }}</td>
            </tr>
            <tr>
                <th>Desde</th>
                <td>{{ experience.dateFrom ? experience.dateFrom|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Hasta</th>
                <td>{{ experience.dateTo ? experience.dateTo|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('experience_index') }}">Volver al Listado</a>

    <a href="{{ path('experience_edit', {'id': experience.id}) }}">Editar</a>

        {{ include('experience/_delete_form.html.twig', {'button_label': 'Borrar'}) }}
{% endblock %}